
biome-distribution:
  # Biome distribution refers to the placement of biomes, this does *NOT*
  # include aspects like terrain height / shape within biomes, or anything
  # else that generates within any given biome.
  
  # These parameters are designed to allow for easy modification of biome distribution,
  # and are injected into the various biome distribution configs via meta-configuration.
  # You can find these configs in the biome-providers directory, most of which contain
  # additional more specific parameters.
  
  continental-scale: 200
  # Controls the scale of land / costal / oceanic distribution. Increasing
  # this produces larger landmasses and larger oceans, and vice-versa when
  # decreasing it.

  temperature-scale: 50
  # Controls the scale of temperature zones. Most biomes are placed according to
  # a temperature map so hot biomes can't generate next to cold biomes, as well as
  # allowing for biomes of similar temperatures to generate together. Increasing this
  # will increase the distance between temperature changes, which results in things like
  # hot and cold biomes generating further apart - and vice versa when decreasing it.

  precipitation-scale: 40
  # Controls the scale of precipitation zones. Same idea as temperature zones, where
  # humid biomes generate away from arid biomes, and biomes of similar precipitation
  # generate together.
  
  elevation-scale: 40
  # Controls the scale of elevation zones. Most land biomes belong to
  # an elevation zone, in addition to temperature and precipitation. How far apart / close
  # together these elevation zones are is determined by this parameter. If you want more
  # gradual changes in the groupings of the elevation of biomes, you can increase this.
  # Conversely, if you want more sudden changes in elevation, you can decrease this.
  # Note - This does not affect how tall the terrain is in individual biomes, just the
  #        elevation map that distributes biomes of similar elevation together!

  variation-scale: 60
  # Controls biome variations within each temperature + precipitation + elevation zone.
  # Some biomes belong to the same groups, and so we have an extra variation map that
  # determines which of these biomes within the same group get generated.

  river-spread-scale: 10
  # Controls how far / close apart rivers generally are, larger scale = further apart
  # rivers, smaller scale = closer packed together rivers.

  volcano-spread: 90
  # Controls how far / close together volcanoes are, larger scale = volcanoes that generate
  # further apart, smaller scale = more packed together volcanoes.

  volcano-radius: 5
  # Controls the radius of all volcanoes, decreasing this too much can result in some
  # glitchy generation for volcanoes filled with fluids above sea level, so keep this in mind
  # if you want smaller volcanoes!

  mushroom-island-spread: 110
  # Controls the distance between mushroom islands (which only generate on deep oceans).
  # Increasing this will spread mushroom islands out more, which effectively makes them more
  # rare, decreasing will make islands closer and therefore more common.
  
  mushroom-island-radius: 4
  # How large any given mushroom island will be.
  
  global-scale: 1
  # Modifies the scale of everything, you can use this parameter to if you
  # want just about every biome to be larger or smaller.
  # By doubling the scale, you double the length & width of everything,
  # e.g. if you have a biome that is 300 blocks wide with a scale of 1, and
  # increase that scale to 2, that biome will generate 600 blocks wide.

# Misc global config stuff

strata: # Controls global Y level ranges of strata
  deepslate:
    top: 7
    bottom: -7
  bedrock:
    top: -60
    bottom: -64

palette-bottom: # Added to the bottom of every palette
  - DEEPSLATE: $meta.yml:strata.deepslate.top
  - BEDROCK: $meta.yml:strata.bedrock.top
  - BLOCK:minecraft:bedrock: $meta.yml:strata.bedrock.bottom