id: OVERWORLD
version: 0.1.0
author: "Astrash, Sancires"

generator: NOISE_3D

addons:
  biome-provider-pipeline: "0.1.+"
  biome-provider-single: "0.1.+"
  chunk-generator-noise-3d: "0.1.+"
  config-biome: "0.1.+"
  config-flora: "0.1.+"
  config-noise-function: "0.1.+"
  config-ore: "0.1.+"
  config-palette: "0.1.+"
  config-distributors: "0.1.+"
  config-locators: "0.1.+"
  config-feature: "0.1.+"
  structure-terrascript-loader: "0.1.+"
  structure-sponge-loader: "0.1.+"
  language-yaml: "0.1.+"
  generation-stage-feature: "0.1.+"
  structure-function-check-noise-3d: "0.1.+"
  palette-block-shortcut: "0.1.+"
  structure-block-shortcut: "0.1.+"
  terrascript-function-sampler: "0.1.+"

# ---
# Biome distribution
# ---
# Several preset biome providers are available to choose from below.
# Choosing which one is in use is as simple as commenting the enabled one
# (by adding a # at the start) and uncommenting the one you wish to use.

# If you want to tweak biome distribution, there are some basic
# parameters that can be found in the meta.yml config file.

# You can also further configure the behaviour of each preset in the
# referenced file(s) below.

# Default biome distribution
biomes: $biome-providers/presets/default.yml:biomes

# Single biome - to change the single biome to use, check the configuration file.
#biomes: $biome-providers/presets/single.yml:biomes

# TODO: Continental - Generates large continents
#biomes: $biome-providers/presets/continental.yml:biomes

# TODO: Water world - Ocean biomes only
#biomes: $biome-providers/presets/water_world.yml:biomes

# TODO: Desert world - Hot biomes only
#biomes: $biome-providers/presets/desert_world.yml:biomes

# TODO: Frozen World - Frozen biomes only
#biomes: $biome-providers/presets/frozen_world.yml:biomes

# Terrain test pipeline
#biomes: $biomes/abstract/terrain/test/pipeline.yml:biomes

# ---
# Population stages
# ---
# Here are the population stages that occur after the initial terrain
# within a chunk is generated. Stages are ordered from top to bottom
# chronologically, where the top stage is executed first.

# If you wish to disable a generation stage, you can simply comment
# it out by prepending it with #, this is useful if you want
# something like a world without ores.

stages:
  - id: preprocessors # Misc features that are treated as small modifications
    type: FEATURE     # to the initial chunk generation.

  - id: lava # Used to generate lava at the bottom of the world
    type: FEATURE

  - id: landforms # Used for things like boulders and features that act
    type: FEATURE # like a part of the terrain.

  - id: slabs # Adds slab versions of some blocks to make terrain look smoother
    type: FEATURE

  - id: ores # Self-explanatory - used to generate ores
    type: FEATURE

  - id: deposits # Adds things like dirt, andesite and gravel patches
    type: FEATURE

  - id: underwater-flora # Used for small features placed underwater like sea-grass
    type: FEATURE

  - id: flora # Used for small features placed on the surface like tall grass and vines
    type: FEATURE

  - id: trees # Used for larger things that generate on the surface like trees, some other
    type: FEATURE # features are also treated as trees like ice spikes.

functions:
  "<<":
    - math/functions/terrace.yml:functions
    - math/functions/lerp.yml:functions
    - math/functions/maskSmooth.yml:functions

samplers:
  "<<":
    - math/samplers/simplex.yml:samplers
