biomes:
  type: EXTRUSION
  extrusions:
    - type: REPLACE
      from: LAND_CAVES
      sampler:
        type: CELLULAR
        return: CellValue
        frequency: 0.005
      to:
        - SELF: 4
        - LUSH_CAVES: 1
        - DRIPSTONE_CAVES: 1
      range:
        min: -16
        max: 48
    - type: REPLACE
      from: LAND_CAVES
      sampler:
        type: OPEN_SIMPLEX_2
        frequency: 0.005
      to:
        - SELF: 4
        - DEEP_DARK: 1
      range:
        min: -64
        max: 0
  provider:
    type: PIPELINE
    resolution: 2
    initial-size: 10
    blend:
      amplitude: 1
      sampler:
        type: WHITE_NOISE
    pipeline:
      # The source controls ocean / coast / land distribution
      source: $biome-providers/sources/basic_continents.yml:source
      stages:
        # Assign zones for volcanic biomes
        - << biome-providers/stages/add_volcanic_zones.yml:stages
        
        # Add mushroom islands
        - << biome-providers/stages/add_mushroom_islands.yml:stages
        
        # Replace deep ocean border with deep ocean
        - << biome-providers/stages/replace_deep_ocean_border.yml:stages
  
        # Split land & coast (determined by the source) into elevation zones
        - << biome-providers/stages/distribute_elevation_zones.yml:stages
  
        # Replace some higher coastal zones with flat ones
        - << biome-providers/stages/flatten_coast_randomly.yml:stages
  
        # Replace volcanic biomes with variants
        - << biome-providers/stages/add_volcanic_variations.yml:stages
  
        # Split elevation zones into temperature zones
        - << biome-providers/stages/distribute_temperature_zones.yml:stages
  
        # Split temperature zones into precipitation zones or singular biomes
        # - Some temperature zones aren't affected by precipitation (such as polar)
        #   and are handled by the next stage instead.
        - << biome-providers/stages/distribute_precipitation_zones.yml:stages
  
        # Choose final biome(s) for any zones not assigned biomes in the previous stage.
        - << biome-providers/stages/distribute_climate_variants.yml:stages
  
        # Biome specific variations
    
        - << biome-providers/stages/expand.yml:stages
  
        - << biome-providers/stages/add_variants.yml:stages
        
        - << biome-providers/stages/expand.yml:stages
        
        - << biome-providers/stages/expand.yml:stages
  
        - << biome-providers/stages/smooth.yml:stages
        - << biome-providers/stages/smooth.yml:stages
        - << biome-providers/stages/smooth.yml:stages
  
  
        - << biome-providers/stages/expand.yml:stages
  
        - << biome-providers/stages/smooth.yml:stages
        - << biome-providers/stages/smooth.yml:stages
        - << biome-providers/stages/smooth.yml:stages
        
        # Add rivers to all biomes
        - << biome-providers/stages/add_rivers.yml:stages