id: ENVIRONMENT_MARINE_RIVER_FROZEN
type: BIOME
abstract: true

colors:
  fog: 0xc0d8ff
  water: 0x2570B5
  water-fog: 0x174985
  sky: 0x7fa1ff
  grass: 0x80B497
  foliage: 0x60A17B

climate:
  precipitation: true
  temperature: 0.5
  temperature-modifier: FROZEN
  downfall: 0.5