id: BASE
type: BIOME
abstract: true
extends:
  - DEPOSITS_DEFAULT
  - ORES_DEFAULT
slant-depth: 15

ocean:
  palette: BLOCK:minecraft:water
  level: 62

features:
  lava:
    - LAVA_FLOOR
  underwater-flora:
    - KELP
    - SEAGRASS
