plantable-blocks:
  - minecraft:mud
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:moss_block
  - minecraft:rooted_dirt

dry-plantable-blocks:
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:moss_block
  - minecraft:rooted_dirt

palm-tree-plantable-blocks:
  - minecraft:sand
  - minecraft:red_sand
  - minecraft:grass_block

aquatic-plantable-blocks:
  - minecraft:mud
  - minecraft:sand
  - minecraft:gravel

sugarcane-plantable-blocks:
  - minecraft:mud
  - minecraft:sand
  - minecraft:red_sand
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:moss_block
  - minecraft:rooted_dirt

dripleaf-plantable-blocks:
  - minecraft:mud
  - minecraft:clay
  - minecraft:coarse_dirt
  - minecraft:dirt
  - minecraft:farmland
  - minecraft:grass_block
  - minecraft:moss_block
  - minecraft:mycelium
  - minecraft:podzol
  - minecraft:rooted_dirt

sculk-plantable-blocks:
  - minecraft:stone
  - minecraft:tuff
  - minecraft:deepslate
  - minecraft:cobbled_deepslate
  - minecraft:chiseled_deepslate
  - minecraft:polished_deepslate
  - minecraft:deepslate_tiles
  - minecraft:cracked_deepslate_tiles
  - minecraft:deepslate_bricks
  - minecraft:cracked_deepslate_bricks
  - minecraft:polished_basalt
  - minecraft:deepslate_tile_wall
  - minecraft:cobbled_deepslate_wall
  - minecraft:polished_deepslate_wall
  - minecraft:deepslate_tile_stairs
  - minecraft:dark_oak_log
  - minecraft:dark_oak_planks
  - minecraft:dark_oak_fence