plantable-blocks:
  - minecraft:mud
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:moss_block
  - minecraft:pale_moss_block
  - minecraft:rooted_dirt
  - minecraft:mycelium

mushroom-plantable-blocks:
  - minecraft:mud
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:moss_block
  - minecraft:pale_moss_block
  - minecraft:rooted_dirt
  - minecraft:mycelium
  - minecraft:mushroom_stem
  - minecraft:red_mushroom_block
  - minecraft:brown_mushroom_block

dry-plantable-blocks:
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:rooted_dirt

dragons-blood-tree-plantable-blocks:
  - minecraft:sand
  - minecraft:gravel
  - minecraft:red_sand
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:rooted_dirt

palm-tree-plantable-blocks:
  - minecraft:sand
  - minecraft:red_sand
  - minecraft:grass_block

aquatic-plantable-blocks:
  - minecraft:mud
  - minecraft:sand
  - minecraft:gravel

seagrass-plantable-blocks:
  - minecraft:mud
  - minecraft:sand
  - minecraft:red_sand
  - minecraft:gravel
  - minecraft:deepslate
  - minecraft:basalt
  - minecraft:oak_planks
  - minecraft:birch_planks
  - minecraft:jungle_planks
  - minecraft:spruce_planks

sugarcane-plantable-blocks:
  - minecraft:mud
  - minecraft:sand
  - minecraft:red_sand
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:moss_block
  - minecraft:pale_moss_block
  - minecraft:rooted_dirt

dry-grass-plantable-blocks:
  - minecraft:mud
  - minecraft:sand
  - minecraft:red_sand
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:moss_block
  - minecraft:rooted_dirt

dripleaf-plantable-blocks:
  - minecraft:mud
  - minecraft:clay
  - minecraft:coarse_dirt
  - minecraft:dirt
  - minecraft:farmland
  - minecraft:grass_block
  - minecraft:moss_block
  - minecraft:pale_moss_block
  - minecraft:mycelium
  - minecraft:podzol
  - minecraft:rooted_dirt

sculk-plantable-blocks:
  - minecraft:stone
  - minecraft:tuff
  - minecraft:deepslate
  - minecraft:cobbled_deepslate
  - minecraft:chiseled_deepslate
  - minecraft:polished_deepslate
  - minecraft:deepslate_tiles
  - minecraft:cracked_deepslate_tiles
  - minecraft:deepslate_bricks
  - minecraft:cracked_deepslate_bricks
  - minecraft:polished_basalt
  - minecraft:deepslate_tile_wall
  - minecraft:cobbled_deepslate_wall
  - minecraft:polished_deepslate_wall
  - minecraft:deepslate_tile_stairs
  - minecraft:dark_oak_log
  - minecraft:dark_oak_planks
  - minecraft:dark_oak_fence
  - minecraft:sand
  - minecraft:gravel
  - minecraft:mud
  - minecraft:smooth_basalt

tree-blocks:
  - minecraft:oak_log
  - minecraft:spruce_log
  - minecraft:birch_log
  - minecraft:jungle_log
  - minecraft:acacia_log
  - minecraft:dark_oak_log
  - minecraft:mangrove_log
  - minecraft:cherry_log
  - minecraft:pale_oak_log
  - minecraft:oak_wood
  - minecraft:spruce_wood
  - minecraft:birch_wood
  - minecraft:jungle_wood
  - minecraft:acacia_wood
  - minecraft:dark_oak_wood
  - minecraft:mangrove_wood
  - minecraft:cherry_wood
  - minecraft:pale_oak_wood
  - minecraft:stripped_oak_log
  - minecraft:stripped_spruce_log
  - minecraft:stripped_birch_log
  - minecraft:stripped_jungle_log
  - minecraft:stripped_acacia_log
  - minecraft:stripped_dark_oak_log
  - minecraft:stripped_mangrove_log
  - minecraft:stripped_cherry_log
  - minecraft:stripped_pale_oak_log
  - minecraft:stripped_oak_wood
  - minecraft:stripped_spruce_wood
  - minecraft:stripped_birch_wood
  - minecraft:stripped_jungle_wood
  - minecraft:stripped_acacia_wood
  - minecraft:stripped_dark_oak_wood
  - minecraft:stripped_mangrove_wood
  - minecraft:stripped_cherry_wood
  - minecraft:stripped_pale_oak_wood
  - minecraft:oak_leaves
  - minecraft:spruce_leaves
  - minecraft:birch_leaves
  - minecraft:jungle_leaves
  - minecraft:acacia_leaves
  - minecraft:dark_oak_leaves
  - minecraft:mangrove_leaves
  - minecraft:cherry_leaves
  - minecraft:pale_oak_leaves
  - minecraft:azalea_leaves
  - minecraft:mushroom_stem
  - minecraft:red_mushroom_block
  - minecraft:brown_mushroom_block