stages:
  - type: REPLACE_LIST
    sampler:
      type: EXPRESSION
      expression: temperature(x, z)

    default-from: land
    default-to:
      - ice-cap:                     &iceCap         1
      - tundra:                      &tundra         1
      - boreal-snowy:                &borealSnowy 1
      - boreal-cold:                 &borealCold     1
      - boreal-warm:                 &borealWarm     1
      - boreal-hot:                  &borealHot      1
      - temperate-cold:              &temperateCold  1
      - temperate-warm:              &temperateWarm  3
      - temperate-hot:               &temperateHot   2
      - tropical-savanna-wet:        &tropicalCold   1
      - tropical-monsoon:            &tropicalWarm   1
      - tropical-rainforest:         &tropicalHot    4
    to:
      coast:
        - polar-coast:               *iceCap
        - polar-coast:               *tundra
        - boreal-coast:              *borealSnowy
        - boreal-coast:              *borealCold
        - boreal-coast:              *borealWarm
        - boreal-coast:              *borealHot
        - temperate-coast:           *temperateCold
        - temperate-coast:           *temperateWarm
        - temperate-coast:           *temperateHot
        - hot-coast:                 *tropicalCold
        - hot-coast:                 *tropicalWarm
        - hot-coast:                 *tropicalHot
      ocean:
        - polar-ocean:               *iceCap
        - polar-ocean:               *tundra
        - boreal-ocean:              *borealSnowy
        - boreal-ocean:              *borealCold
        - boreal-ocean:              *borealWarm
        - boreal-ocean:              *borealHot
        - temperate-ocean:           *temperateCold
        - temperate-ocean:           *temperateWarm
        - temperate-ocean:           *temperateHot
        - hot-ocean:                 *tropicalCold
        - hot-ocean:                 *tropicalWarm  
        - hot-ocean:                 *tropicalHot
      mesa:
        - polar-mesa:                *iceCap
        - polar-mesa:                *tundra
        - boreal-mesa:               *borealSnowy
        - boreal-mesa:               *borealCold
        - boreal-mesa:               *borealWarm
        - boreal-mesa:               *borealHot
        - temperate-mesa:            *temperateCold
        - temperate-mesa:            *temperateWarm
        - temperate-mesa:            *temperateHot
        - hot-mesa:                  *tropicalCold
        - hot-mesa:                  *tropicalWarm
        - hot-mesa:                  *tropicalHot
      crater-lake:
        - polar-crater-lake:         *iceCap
        - polar-crater-lake:         *tundra
        - boreal-crater-lake:        *borealSnowy
        - boreal-crater-lake:        *borealCold
        - boreal-crater-lake:        *borealWarm
        - boreal-crater-lake:        *borealHot
        - temperate-crater-lake:     *temperateCold
        - temperate-crater-lake:     *temperateWarm
        - temperate-crater-lake:     *temperateHot
        - hot-crater-lake:           *tropicalCold
        - hot-crater-lake:           *tropicalWarm
        - hot-crater-lake:           *tropicalHot
      extinct-volcano:
        - polar-extinct-volcano:     *iceCap
        - polar-extinct-volcano:     *tundra
        - boreal-extinct-volcano:    *borealSnowy
        - boreal-extinct-volcano:    *borealCold
        - boreal-extinct-volcano:    *borealWarm
        - boreal-extinct-volcano:    *borealHot
        - temperate-extinct-volcano: *temperateCold
        - temperate-extinct-volcano: *temperateWarm
        - temperate-extinct-volcano: *temperateHot
        - hot-extinct-volcano:       *tropicalCold
        - hot-extinct-volcano:       *tropicalWarm
        - hot-extinct-volcano:       *tropicalHot