id: ENVIRONMENT_MARINE_OCEAN_WARM
type: BIOME
abstract: true

colors:
  fog: 0xc0d8ff
  water: 0x02B0E5
  water-fog: 0x0289d5
  sky: 0x7ba4ff
  grass: 0x8EB971
  foliage: 0x71A74D

climate:
  precipitation: true
  temperature: 0.5
  downfall: 0.5