stages:
  # Climate variations
  - type: REPLACE_LIST
    default-from: desert-variants
    default-to:
      - DESERT: 5
      - ROCKY_DESERT: 3
      - desert-spikes-microvariants: 1
    to:
      jungle-flats-variants:
        - jungle-flats-microvariants: 5
        - SWAMP: 1
      evergreen-flats-variants:
        - EVERGREEN_FLATS: 5
        - FLOWERING_FLATS: 3
      plains-variants:
        - plains-microvariants: 3
        - PRAIRIE: 3
      birch-flats-variants:
        - BIRCH_FLATS: 3
        - AUTUMNAL_FLATS: 2
      jungle-variants:
        - jungle-microvariants: 4
        - BAMBOO_PONDS: 1
      evergreen-forest-variants:
        - EVERGREEN_FOREST: 5
        - FLOWERING_FOREST: 3
        - EVERGREEN_OVERHANGS: 1
      birch-forest-variants:
        - BIRCH_FOREST: 3
        - AUTUMNAL_FOREST: 1
      birch-forest-hills-variants:
        - BIRCH_FOREST_HILLS: 5
        - AUTUMNAL_FOREST_HILLS: 3
        - FLOWERING_AUTUMNAL_FOREST_HILLS: 1
      badlands-variants:
        - BADLANDS_MOUNTAINS: 2
        - DESERT_PILLARS: 1
        - BADLANDS_BUTTES: 2
        - ERODED_BADLANDS_BUTTES: 1
        - ARID_HIGHLANDS: 1
      forest-hills-variants:
        - FOREST_HILLS: 5
        - FLOWERING_FOREST_HILLS: 3
      wild-mountains-variants:
        - WILD_BUMPY_MOUNTAINS: 3
      temperate-mountains-variants:
        - HIGHLANDS: 4
        - TEMPERATE_MOUNTAINS: 8
        - SAKURA_MOUNTAINS: 4
    sampler:
      dimensions: 2
      type: CELLULAR
      return: CellValue
      salt: 42342
      frequency: 0.06 / ${meta.yml:biome-distribution.global-scale}

  # Direct variants - color variations, etc
  - type: REPLACE_LIST
    default-from: desert-spikes-microvariants
    default-to:
      - DESERT_SPIKES: 6
      - DESERT_SPIKES_GOLD: 1
    to:
      DRY_TEMPERATE_MOUNTAINS:
        - SELF: 2
        - DRY_TEMPERATE_WHITE_MOUNTAINS: 1
      TAIGA_HILLS:
        - SELF: 9
        - REDWOOD_FOREST_HILLS: 1
      jungle-flats-microvariants:
        - JUNGLE_FLATS: 4
        - BAMBOO_JUNGLE_FLATS: 2
        - PALM_FOREST: 2
      jungle-microvariants:
        - JUNGLE: 3
        - BAMBOO_JUNGLE: 1
      plains-microvariants:
        - PLAINS: 3
        - SUNFLOWER_PLAINS: 1
      JUNGLE_HILLS:
        - SELF: 3
        - BAMBOO_JUNGLE_HILLS: 1
      JUNGLE_MOUNTAINS:
        - SELF: 3
        - BAMBOO_JUNGLE_MOUNTAINS: 1
      desert-flats-microvariants:
        - DESERT_FLATS: 7
        - SALT_FLATS: 1
      
    sampler:
      dimensions: 2
      type: CELLULAR
      return: CellValue
      frequency: 0.3 / ${meta.yml:biome-distribution.global-scale}
      salt: 34534
