# The samplers that control the shape of rivers, you can find various presets
# in the biome-providers/stages/river-samplers/ folder.
riverSampler: &riverSampler $biome-providers/stages/river-samplers/default.yml:sampler
# To pick the preset, simply change the file reference above ^
# You can further edit and customize the parameters of presets within their own files.

stages:
  # Regular rivers + biome specific river variants
  - type: REPLACE_LIST
    default-from: USE_RIVER
    default-to:
      - SELF: 1
      - RIVER: 1
    to:
      TEMPERATE_MOUNTAINS:
        - SELF: 1
        - TEMPERATE_MOUNTAINS_RIVER: 1
      MOUNTAINS:
        - SELF: 1
        - MOUNTAINS_RIVER: 1
      XERIC_MOUNTAINS:
        - SELF: 1
        - XERIC_MOUNTAINS_RIVER: 1
      BADLANDS_MOUNTAINS:
        - SELF: 1
        - BADLANDS_MOUNTAINS_RIVER: 1
      DRY_TEMPERATE_MOUNTAINS:
        - SELF: 1
        - DRY_TEMPERATE_MOUNTAINS_RIVER: 1
      DRY_TEMPERATE_WHITE_MOUNTAINS:
        - SELF: 1
        - DRY_TEMPERATE_WHITE_MOUNTAINS_RIVER: 1
      SNOWY_MOUNTAINS:
        - SELF: 1
        - SNOWY_MOUNTAINS_RIVER: 1
      SNOWY_TERRACED_MOUNTAINS:
        - SELF: 1
        - SNOWY_TERRACED_MOUNTAINS_RIVER: 1
      SNOWY_ERODED_TERRACED_MOUNTAINS:
        - SELF: 1
        - SNOWY_ERODED_TERRACED_MOUNTAINS_RIVER: 1
    sampler: *riverSampler
  # Flat Rivers
  - type: REPLACE
    from: USE_RIVER_FLAT
    to:
      - SELF: 1
      - MARSH: 2
      - RIVER: 2
    sampler: *riverSampler
  # Flat Rivers
  - type: REPLACE
    from: USE_RIVER_FLAT_SWAMP
    to:
      - SELF: 1
      - SWAMP: 2
      - RIVER: 2
    sampler: *riverSampler
  # Flat Coastal Rivers
  - type: REPLACE
    from: USE_RIVER_FLAT_COASTAL
    to:
      - SELF: 1
      - MANGROVE_SWAMP: 2
      - RIVER: 2
    sampler: *riverSampler
  # Frozen Rivers
  - type: REPLACE
    from: USE_FROZEN_RIVER
    to:
      - SELF: 1
      - FROZEN_RIVER: 1
    sampler: *riverSampler
  # Flat Frozen Rivers
  - type: REPLACE
    from: USE_FROZEN_RIVER_FLAT
    to:
      - SELF: 1
      - FROZEN_MARSH: 2
      - FROZEN_RIVER: 2
    sampler: *riverSampler