stages:
  - type: REPLACE
    from: BIOME:DESERT
    to:
      - SELF: 5
      - ROCKY_DESERT: 3
      - DESERT_SPIKES: 1
    sampler:
      dimensions: 2
      type: CELLULAR
      return: CellValue
      frequency: 0.03 / ${meta.yml:biome-distribution.global-scale}

  - type: REPLACE
    from: BIOME:DESERT_SPIKES
    to:
      - SELF: 6
      - DESERT_SPIKES_GOLD: 1
    sampler:
      dimensions: 2
      type: CELLULAR
      return: CellValue
      frequency: 0.06 / ${meta.yml:biome-distribution.global-scale}
      salt: 23