
# Uses warped cellular distance to determine where volcanoes are placed.
# The output is modified to allow users to define the spread and radius easily.
zone-sampler:
  type: EXPRESSION
  expression: split((noise(x/spread,z/spread)+1)*4/(radius/spread)-1)
  variables:
    spread: &spread 0+${meta.yml:biome-distribution.global-scale} * ${meta.yml:biome-distribution.volcano-spread}
    radius: 0+${meta.yml:biome-distribution.global-scale} * ${meta.yml:biome-distribution.volcano-radius}
  functions:
    split:
      arguments: [x]
      expression: if(x<0,x,1)
  samplers:
    noise: &noise
      dimensions: 2
      type: DOMAIN_WARP
      amplitude: 0.01
      warp:
        type: OPEN_SIMPLEX_2
        salt: 3912
        frequency: 10
      sampler: &cellular
        type: CELLULAR
        salt: 5912
        frequency: 1

# Variations use the same cellular noise as above but return the cell value
# instead to determine the variation.
# This sampler is used in the add_volcanic_variations.yml file.
variation-sampler:
  type: EXPRESSION
  expression: noise(x/spread,z/spread)
  variables:
    spread: *spread
  samplers:
    noise:
      <<: *noise
      sampler:
        <<: *cellular
        return: CellValue

volcano-area-weight: &volcano-area-weight 14 # Summed weights allocated to volcanic area

stages:
  - type: REPLACE_LIST
    default-from: deep-ocean
    default-to:
      # Volcano area - The weights should sum to volcano-area-weight.
      - volcano-pit: 1
      - volcano-pit-edge: 1
      - volcano-base-edge: 2
      - volcano-base: 4
      - mountains-small: 3
      - coast-mountains-small: 3
      # Non-volcano area
      - deep-ocean: *volcano-area-weight
    to:
      deep-ocean-border:
        # Volcano area
        - volcano-pit: 1
        - volcano-pit-edge: 1
        - volcano-base-edge: 2
        - volcano-base: 4
        - mountains-small: 3
        - coast-mountains-small: 3
        # Non-volcano area
        - deep-ocean-border: *volcano-area-weight
      ocean:
        # Volcano area
        - volcano-pit: 1
        - volcano-pit-edge: 1
        - volcano-base-edge: 2
        - volcano-base: 4
        - hills-large: 3
        - coast-hills: 3
        # Non-volcano area
        - ocean: *volcano-area-weight
      coast:
        # Volcano area
        - volcano-pit: 1
        - volcano-pit-edge: 1
        - volcano-base-edge: 2
        - volcano-base: 4
        - coast-mountains-small: 6
        # Non-volcano area
        - coast: *volcano-area-weight
      land:
        # Volcano area
        - volcano-pit: 1
        - volcano-pit-edge: 1
        - volcano-base-edge: 2
        - volcano-base: 4
        - land: 6
        # Non-volcano area
        - land: *volcano-area-weight
    sampler: $biome-providers/stages/add_volcanic_zones.yml:zone-sampler
