
# Replaces temperature zones with the relevant biome,
# or a precipitation zone, which contains climate variants,
# handled in the distribute_variants.yml file.

# Aquatic, coastal (except tropical coastal), and polar zones aren't affected
# by precipitation and are distributed via the distribute_variants.yml file instead.

precipitation-map: &precipitation-map
  dimensions: 2
  type: FBM
  octaves: 2
  sampler:
    type: OPEN_SIMPLEX_2
    salt: 5055
    frequency: 1 / ${meta.yml:biome-distribution.precipitation-scale} / ${meta.yml:biome-distribution.global-scale}

stages:
  - type: REPLACE_LIST
    sampler: *precipitation-map

    # --------------------------------------------
    #                   Flat Biomes
    # --------------------------------------------

    default-from: flat-tropical
    default-to:

  # -------------
  # Flat Tropical Humid
  # -------------
      - jungle-flats-variants: 5
  # -------------
  # Flat Tropical Semi-Humid
  # -------------
      - GRASS_SAVANNA: 1
      - SAVANNA: 1
  # -------------
  # Flat Tropical Semi-Arid
  # -------------
      - WARM_STEPPE: 1
  # -------------
  # Flat Tropical Semi-Arid
  # -------------
      - XERIC_PLAINS: 3
  # -------------
  # Flat Tropical Arid
  # -------------
      - desert-flats-microvariants: 4

    to:
      flat-subtropical:
    # -------------
    # Flat Subtropical Semi Humid
    # -------------
        - evergreen-flats-variants: 8
    # -------------
    # Flat Subtropical Semi-Arid
    # -------------
        - WARM_STEPPE: 3
    # -------------
    # Flat Subtropical Arid
    # -------------
        - XERIC_PLAINS: 5

      flat-temperate:
    # -------------
    # Flat Temperate Humid
    # -------------
        - FOREST_FLATS: 5
    # -------------
    # Flat Temperate Semi-Humid
    # -------------
        - plains-variants: 5
    # -------------
    # Flat Temperate Semi-Arid
    # -------------
        - STEPPE: 3
    # -------------
    # Flat Temperate Arid (Mediterranean)
    # -------------
        - OAK_SAVANNA: 4

      flat-boreal:
    # -------------
    # Flat Boreal Humid (Wetter Forests)
    # -------------
        - birch-flats-variants: 3
    # -------------
    # Flat Boreal Semi-Humid (Dryer Forests)
    # -------------
        - TAIGA_FLATS: 3

    # --------------------------------------------
    #               Small Hills Biomes
    # --------------------------------------------

      hills-small-tropical:
        # -------------
        # Small Hills Tropical Humid
        # -------------
        - jungle-variants: 5
        
        # -------------
        # Small Hills Tropical Semi-Humid
        # -------------
        - GRASS_SAVANNA_LOW_HILLS: 2
        - SAVANNA_LOW_HILLS: 2
        # -------------
        # Small Hills Tropical Semi-Arid
        # -------------
        - WARM_LOW_HILLS: 3
        # -------------
        # Small Hills Tropical Arid
        # -------------
        - desert-variants: 7

      hills-small-subtropical:
        # -------------
        # Small Hills Subtropical Humid
        # -------------
        - RAINFOREST: 5
        # -------------
        # Small Hills Subtropical Semi Humid
        # -------------
        - evergreen-forest-variants: 6
        # -------------
        # Small Hills Subtropical Semi-Arid
        # -------------
        - WARM_LOW_HILLS: 4
        # -------------
        # Small Hills Subtropical Arid
        # -------------
        - XERIC_LOW_HILLS: 5

      hills-small-temperate:
        # -------------
        # Small Hills Temperate Semi-Humid
        # -------------
        - FOREST: 3
        # -------------
        # Small Hills Temperate Semi-Arid
        # -------------
        - WOODED_BUTTES: 2

      hills-small-boreal:
        # -------------
        # Small Hills Boreal Humid (Wetter Forests)
        # -------------
        - birch-forest-variants: 3
        # -------------
        # Small Hills Boreal Semi-Humid (Dryer Forests)
        # -------------
        - TAIGA: 3

    # --------------------------------------------
    #              Large Hills Biomes
    # --------------------------------------------

      hills-large-tropical:
        # -------------
        # Large Hills Tropical Humid
        # -------------
        - JUNGLE_HILLS: 5
        # -------------
        # Large Hills Tropical Semi-Humid
        # -------------
        - GRASS_SAVANNA_HILLS: 3
        - SAVANNA_HILLS: 3
        # -------------
        # Large Hills Tropical Semi-Arid
        # -------------
        - WARM_HILLS: 2
        # -------------
        # Large Hills Tropical Arid
        # -------------
        - ARID_SPIKES: 5

      hills-large-subtropical:
        # -------------
        # Large Hills Subtropical Humid
        # -------------
        - RAINFOREST_HILLS: 5
        # -------------
        # Large Hills Subtropical Semi-Humid
        # -------------
        - EVERGREEN_FOREST_HILLS: 6
        # -------------
        # Large Hills Subtropical Semi-Arid
        # -------------
        - MOORLAND: 2
        # -------------
        # Large Hills Subtropical Arid
        # -------------
        - XERIC_HILLS: 5

      hills-large-temperate:
        # -------------
        # Large Hills Temperate Semi-Humid
        # -------------
        - forest-hills-variants: 8
        # -------------
        # Large Hills Temperate Semi-Arid
        # -------------
        - SHRUBLAND: 4
        # -------------

      hills-large-boreal:
        # -------------
        # Large Hills Boreal Semi-Humid
        # -------------
        - birch-forest-hills-variants: 9
        # -------------
        # Large Hills Boreal Semi-Arid
        # -------------
        - TAIGA_HILLS: 11

    # --------------------------------------------
    #            Small Mountains Biomes
    # --------------------------------------------

      mountains-small-tropical:
        # -------------
        # Small Mountains Tropical Humid
        # -------------
        - OVERGROWN_CLIFFS: 6
        # -------------
        # Small Mountains Tropical Semi-Humid
        # -------------
        - SAVANNA_OVERHANGS: 1
        # -------------
        # Small Mountains Tropical Semi-Arid
        # -------------
        - XERIC_MOUNTAINS: 3
        # -------------
        # Small Mountains Tropical Arid
        # -------------
        - badlands-variants: 6
        - ARID_HIGHLANDS: 5
        
      mountains-small-subtropical:
        # -------------
        # Small Mountains Subtropical Semi-Humid
        # -------------
        - MONSOON_MOUNTAINS: 5
        # -------------
        # Small Mountains Subtropical Semi-Humid
        # -------------
        - wild-mountains-variants: 3
        # -------------
        # Small Mountains Subtropical Semi-Arid
        # -------------
        - ROCKY_BUMPY_MOUNTAINS: 4
        # -------------
        # Small Mountains Subtropical Arid
        # -------------
        - DRY_ROCKY_BUMPY_MOUNTAINS: 5

      mountains-small-temperate:
        # -------------
        # Mountains Temperate Semi-Humid
        # -------------
        - HIGHLANDS: 4
        - TEMPERATE_MOUNTAINS: 8

      mountains-small-boreal:
        # -------------
        # Mountains Boreal Semi-Humid
        # -------------
        - SNOWY_ERODED_TERRACED_MOUNTAINS: 1
        # -------------
        # Mountains Boreal Semi-Arid
        # -------------
        - MOUNTAINS: 3

    # --------------------------------------------
    #            Large Mountains Biomes
    # --------------------------------------------

      mountains-large-tropical:
        # -------------
        # Large Mountains Tropical Humid
        # -------------
        - JUNGLE_MOUNTAINS: 5
        # -------------
        # Large Mountains Tropical Semi-Humid
        # -------------
        - WILD_HIGHLANDS: 5
        # -------------
        # Large Mountains Tropical Semi-Arid
        # -------------
        - DRY_WILD_HIGHLANDS: 3
        # -------------
        # Large Mountains Tropical Arid
        # -------------
        - CRACKED_BADLANDS_PLATEAU: 5

      mountains-large-subtropical:
        # -------------
        # Large Mountains Subtropical Humid
        # -------------
        - LARGE_MONSOON_MOUNTAINS: 1

      mountains-large-temperate:
        # -------------
        # Large Mountains Temperate Semi-Humid
        # -------------
        - TEMPERATE_ALPHA_MOUNTAINS: 4
        # -------------
        # Large Mountains Temperate Semi-Arid
        # -------------
        - DRY_TEMPERATE_MOUNTAINS: 3

      mountains-large-boreal:
        # -------------
        # Large Mountains Boreal Semi-Humid
        # -------------
        - SNOWY_ERODED_TERRACED_MOUNTAINS: 1

    # --------------------------------------------
    #        Coastal Small Mountains Biomes
    # --------------------------------------------

    coast-mountains-small-tropical:
      # -------------
      # Coastal Small Mountains Tropical Humid
      # -------------
      - coast-mountains-small-tropical-humid: 1
      # -------------
      # Coastal Small Mountains Tropical Semi Humid & Semi Arid
      # -------------
      - coast-mountains-small-tropical: 2
      # -------------
      # Coastal Small Mountains Tropical Arid
      # -------------
      - coast-mountains-small-tropical-arid: 1
