
# Replaces temperature zones with the relevant biome,
# or a precipitation zone, which contains climate variants,
# handled in the distribute_variants.yml file.

# Aquatic, coastal (except tropical coastal), and polar zones aren't affected
# by precipitation and are distributed via the distribute_variants.yml file instead.

precipitation-map: &precipitation-map
  dimensions: 2
  type: FBM
  octaves: 2
  sampler:
    type: OPEN_SIMPLEX_2
    salt: 5055
    frequency: 1 / ${meta.yml:biome-distribution.precipitation-scale} / ${meta.yml:biome-distribution.global-scale}

stages:
  - type: REPLACE_LIST
    sampler: *precipitation-map

    # --------------------------------------------
    #                   Flat Biomes
    # --------------------------------------------

    default-from: flat-tropical
    default-to:

  # -------------
  # Flat Tropical Humid
  # -------------
      - JUNGLE_FLATS: 5
      - SWAMP: 2
      - BAMBOO_PONDS: 1
  # -------------
  # Flat Tropical Semi-Humid
  # -------------
      - GRASS_SAVANNA: 1
      - SAVANNA: 1
  # -------------
  # Flat Tropical Semi-Arid
  # -------------
      - WARM_STEPPE: 1
  # -------------
  # Flat Tropical Semi-Arid
  # -------------
      - XERIC_PLAINS: 3
      - SALT_FLATS: 1

    to:
      flat-subtropical:
    # -------------
    # Flat Subtropical Semi Humid
    # -------------
        - EVERGREEN_FLATS: 5
        - FLOWERING_FLATS: 3
    # -------------
    # Flat Subtropical Semi-Arid
    # -------------
        - WARM_STEPPE: 3
    # -------------
    # Flat Subtropical Arid
    # -------------
        - XERIC_PLAINS: 1

      flat-temperate:
    # -------------
    # Flat Temperate Semi-Humid
    # -------------
        - FOREST_FLATS: 5
    # -------------
    # Flat Temperate Semi-Arid
    # -------------
        - PLAINS: 3
        - PRAIRIE: 3
        - STEPPE: 3
        - SUNFLOWER_PLAINS: 1
    # -------------
    # Flat Temperate Arid (Mediterranean)
    # -------------
        - OAK_SAVANNA: 1

      flat-boreal:
    # -------------
    # Flat Boreal Humid (Wetter Forests)
    # -------------
        - AUTUMNAL_FLATS: 1
        - BIRCH_FLATS: 2
    # -------------
    # Flat Boreal Semi-Humid (Dryer Forests)
    # -------------
        - TAIGA_FLATS: 3

    # --------------------------------------------
    #               Small Hills Biomes
    # --------------------------------------------

      hills-small-tropical:
        # -------------
        # Small Hills Tropical Humid
        # -------------
        - JUNGLE: 3
        # -------------
        # Small Hills Tropical Semi-Humid
        # -------------
        - GRASS_SAVANNA_LOW_HILLS: 2
        - SAVANNA_LOW_HILLS: 2
        # -------------
        # Small Hills Tropical Semi-Arid
        # -------------
        - WARM_LOW_HILLS: 1
        # -------------
        # Small Hills Tropical Arid
        # -------------
        - DESERT: 6
        - BADLANDS_BUTTES: 1

      hills-small-subtropical:
        # -------------
        # Small Hills Subtropical Humid
        # -------------
        - RAINFOREST: 1
        # -------------
        # Small Hills Subtropical Semi Humid
        # -------------
        - EVERGREEN_FOREST: 5
        - FLOWERING_FOREST: 3
        # -------------
        # Small Hills Subtropical Semi-Arid
        # -------------
        - WARM_LOW_HILLS: 3
        # -------------
        # Small Hills Subtropical Arid
        # -------------
        - XERIC_LOW_HILLS: 1

      hills-small-temperate:
        # -------------
        # Small Hills Temperate Semi-Humid
        # -------------
        - FOREST: 3
        # -------------
        # Small Hills Temperate Semi-Arid
        # -------------
        - WOODED_BUTTES: 1

      hills-small-boreal:
        # -------------
        # Small Hills Boreal Humid (Wetter Forests)
        # -------------
        - AUTUMNAL_FOREST: 1
        - BIRCH_FOREST: 2
        # -------------
        # Small Hills Boreal Semi-Humid (Dryer Forests)
        # -------------
        - TAIGA: 3

    # --------------------------------------------
    #              Large Hills Biomes
    # --------------------------------------------

      hills-large-tropical:
        # -------------
        # Large Hills Tropical Humid
        # -------------
        - JUNGLE_HILLS: 5
        # -------------
        # Large Hills Tropical Semi-Humid
        # -------------
        - GRASS_SAVANNA_HILLS: 3
        - SAVANNA_HILLS: 3
        # -------------
        # Large Hills Tropical Semi-Arid
        # -------------
        - WARM_HILLS: 3
        # -------------
        # Large Hills Tropical Arid
        # -------------
        - XERIC_HILLS: 5
        - ARID_SPIKES: 1

      hills-large-subtropical:
        # -------------
        # Large Hills Subtropical Humid
        # -------------
        - RAINFOREST_HILLS: 3
        # -------------
        # Large Hills Subtropical Semi-Humid
        # -------------
        - EVERGREEN_FOREST: 5
        - FLOWERING_FOREST: 3
        # -------------
        # Large Hills Subtropical Semi-Arid
        # -------------
        - MOORLAND: 2
        # -------------
        # Large Hills Subtropical Arid
        # -------------
        - XERIC_HILLS: 3
        - ARID_SPIKES: 2

      hills-large-temperate:
        # -------------
        # Large Hills Temperate Semi-Humid
        # -------------
        - FOREST: 8
        # -------------
        # Large Hills Temperate Semi-Arid
        # -------------
        - SHRUBLAND: 2
        # -------------

      hills-large-boreal:
        # -------------
        # Large Hills Boreal Semi-Humid
        # -------------
        - BIRCH_FOREST_HILLS: 5
        - AUTUMNAL_FOREST_HILLS: 3
        - FLOWERING_AUTUMNAL_FOREST_HILLS: 1
        # -------------
        # Large Hills Boreal Semi-Arid
        # -------------
        - TAIGA_HILLS: 8
        - REDWOOD_FOREST_HILLS: 4

    # --------------------------------------------
    #            Small Mountains Biomes
    # --------------------------------------------

      mountains-small-tropical:
        # -------------
        # Small Mountains Tropical Humid
        # -------------
        - OVERGROWN_CLIFFS: 3
        # -------------
        # Small Mountains Tropical Semi-Humid
        # -------------
        - SAVANNA_OVERHANGS: 1
        # -------------
        # Small Mountains Tropical Semi-Arid
        # -------------
        - XERIC_MOUNTAINS: 3
        # -------------
        # Small Mountains Tropical Arid
        # -------------
        - BADLANDS_MOUNTAINS: 3
        - DESERT_PILLARS: 3

      mountains-small-subtropical:
        # -------------
        # Small Mountains Subtropical Semi-Humid
        # -------------
        - MONSOON_MOUNTAINS: 3
        # -------------
        # Small Mountains Subtropical Semi-Humid
        # -------------
        - WILD_BUMPY_MOUNTAINS: 3
        - EVERGREEN_OVERHANGS: 1
        # -------------
        # Small Mountains Subtropical Semi-Arid
        # -------------
        - ROCKY_BUMPY_MOUNTAINS: 3
        - XERIC_MOUNTAINS: 1
        # -------------
        # Small Mountains Subtropical Arid
        # -------------
        - DRY_ROCKY_BUMPY_MOUNTAINS: 3
        - BADLANDS_MOUNTAINS: 1
        - DESERT_PILLARS: 1

      mountains-small-temperate:
        # -------------
        # Mountains Temperate Semi-Humid
        # -------------
        - HIGHLANDS: 4
        - TEMPERATE_MOUNTAINS: 8

      mountains-small-boreal:
        # -------------
        # Mountains Boreal Semi-Humid
        # -------------
        - SNOWY_ERODED_TERRACED_MOUNTAINS: 1
        # -------------
        # Mountains Boreal Semi-Arid
        # -------------
        - MOUNTAINS: 3

    # --------------------------------------------
    #            Large Mountains Biomes
    # --------------------------------------------

      mountains-large-tropical:
        # -------------
        # Large Mountains Tropical Humid
        # -------------
        - JUNGLE_MOUNTAINS: 5
        # -------------
        # Large Mountains Tropical Semi-Humid
        # -------------
        - WILD_HIGHLANDS: 5
        # -------------
        # Large Mountains Tropical Semi-Arid
        # -------------
        - DRY_WILD_HIGHLANDS: 3
        # -------------
        # Large Mountains Tropical Arid
        # -------------
        - CRACKED_BADLANDS_PLATEAU: 3

      mountains-large-subtropical:
        # -------------
        # Large Mountains Subtropical Humid
        # -------------
        - LARGE_MONSOON_MOUNTAINS: 1

      mountains-large-temperate:
        # -------------
        # Large Mountains Temperate Semi-Humid
        # -------------
        - TEMPERATE_ALPHA_MOUNTAINS: 3
        # -------------
        # Large Mountains Temperate Semi-Arid
        # -------------
        - DRY_TEMPERATE_MOUNTAINS: 1
        - DRY_TEMPERATE_WHITE_MOUNTAINS: 1

      mountains-large-boreal:
        # -------------
        # Large Mountains Boreal Semi-Humid
        # -------------
        - SNOWY_ERODED_TERRACED_MOUNTAINS: 1

    # --------------------------------------------
    #        Coastal Small Mountains Biomes
    # --------------------------------------------

    coast-mountains-small-tropical:
      # -------------
      # Coastal Small Mountains Tropical Humid
      # -------------
      - coast-mountains-small-tropical-humid: 1
      # -------------
      # Coastal Small Mountains Tropical Semi Humid & Semi Arid
      # -------------
      - coast-mountains-small-tropical: 2
      # -------------
      # Coastal Small Mountains Tropical Arid
      # -------------
      - coast-mountains-small-tropical-arid: 1
