
# Splits land and coastal zones into different elevation zones.
# These elevation zones are further divided into temperature zones
# in the distribute_temperature_zones.yml file.

elevation-map: &elevation-map
  dimensions: 2
  type: FBM
  octaves: 3
  sampler:
    type: OPEN_SIMPLEX_2
    salt: 2313
    frequency: 1 / ${meta.yml:biome-distribution.elevation-scale} / ${meta.yml:biome-distribution.global-scale}

stages:
  - type: REPLACE_LIST
    sampler: *elevation-map

    default-from: coast
    default-to:
      - coast-flat: 2
      - coast-hills: 1
      - coast-hills: 1
      - coast-mountains-small: 1
      - coast-mountains-large: 2
    to:
      land:
#        - flat: 2
        - hills-small: 1
        - hills-large: 1
        - mountains-small: 1
        - mountains-large: 2
